subquery/network-app

.env.staging, package.json, src/components/Spinner/Spinner.tsx, src/components/StepButton/index.tsx, src/components/TransactionModal/TransactionModal.tsx, src/components/Typography/Typography.tsx, src/pages/account/MyAccount/MyAccount.tsx, src/pages/consumer/MyFlexPlans/BillingAction.tsx, src/pages/consumer/MyOffers/CreateOffer/CreateOffer.tsx, src/pages/swap/SwapForm.tsx, vite.config.js, yarn.lock
- Minify when bundle.
- Tree-shaking @ant-design/icons
Will reduce size ~1MB.
=> feat: minify the prod size.

src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/TopIndexers/TopIndexersList.tsx, src/router/routes.ts
=> hotfix:hide indexer profile

.github/workflows/dev-build.yml
=> fix: change workflow

.github/workflows/dev-build.yml, .github/workflows/staging-build.yml
Update deploy pipeline for new dev env
|before|after|
|-|-|
=> Ianhe8x patch ci

src/hooks/useEra.ts, src/pages/delegator/DoDelegate/DoDelegate.tsx, src/pages/indexer/IndexerProfile/IndexerProfile.tsx
Better error handling for delegate for now.
=> feat: retry when delegate load error

src/pages/delegator/AllIndexers/AllIndexers.tsx
For all indexer pages, need login to continue. Otherwise there have a `noNetwork` error.
=> fix: need login when check all indexers page 

src/pages/dashboard/components/EraCard/EraCard.tsx
- Fix dashboard era hours tooltip showing.
[SQN-1902](https://onfinality.atlassian.net/browse/SQN-1902)
=> fix(SQN-1902): dashboard era hours tooltip showing

package.json, yarn.lock
- Need to deploy this change to Kepler
=> Upgrade apollo-link

src/pages/consumer/Playground/FlexPlayground.tsx
Ticket: [SQN-1901](https://onfinality.atlassian.net/browse/SQN-1901)
=> fix(SQN-1901): flex playground

package.json, src/components/IndexerDetails/IndexerDetails.module.less, src/components/IndexerDetails/IndexerName.tsx, src/components/IndexerDetails/Row.tsx, src/pages/account/MyAccount/Header.tsx, src/pages/consumer/MyFlexPlans/MyFlexPlanTable.tsx, src/pages/consumer/Playground/FlexPlayground.tsx, src/pages/consumer/Playground/SAPlayground.tsx, src/pages/consumer/ServiceAgreements/ServiceAgreementsTable.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/TopIndexers/TopIndexersList.tsx, src/pages/explorer/FlexPlans/FlexPlans.tsx, src/pages/indexer/IndexerProfile/IndexerProfile.tsx, src/pages/indexer/MyDelegators/OwnDelegator.tsx, yarn.lock
Ticket: [SQN-1873](https://onfinality.atlassian.net/browse/SQN-1873)
=> feat(SQN-1873): new version avatar

src/components/IndexerDetails/IndexerName.tsx, src/pages/consumer/ServiceAgreements/ServiceAgreementsTable.tsx
Show address instead of name when indexer/consumer/delegator in table.
=> feat: show address instead of name for who don't have name

.env
For release prepare, change the deploymentId to staging version.
=> chore: change deployment id

src/i18n/en/delegator.ts, src/i18n/en/global.ts, src/pages/account/Rewards/Rewards.tsx, src/pages/account/Withdrawn/Locked/Home/Locked.tsx
- Handling the type of `Commission` and `Merge`.
Ticket: [SQN-1940](https://onfinality.atlassian.net/browse/SQN-1940)
=> feat(SQN-1940): improve rewards and withdrawals wording tips

.env, .env.staging, .env.testnet, package.json, src/hooks/useAirdropKyc.ts, src/pages/swap/Swap.tsx, src/pages/swap/SwapForm.tsx, yarn.lock
- Add KYC and tradeLimitation check for swap.
Ticket: [SQN-1944](https://onfinality.atlassian.net/browse/SQN-1944)
=> feat(SQN-1944): kyc

src/hooks/useSwapData.tsx, src/pages/swap/Swap.tsx, src/pages/swap/SwapForm.tsx
- Improve KYC tips box.
- Add limitation error tips for `kSQT -> USDC`.
- Add limitation tips for out of lifetime limitation.
=> fix: whitelist alert box

.env.testnet, src/pages/swap/Swap.tsx
- Improve re-load condition of limitation.
- Make cache for limitation.
=> feat: add cache for swap limitation

src/hooks/useStableCoin.tsx
=> fix: conver price

src/components/IndexerDetails/PlansTable.tsx, src/hooks/useStableCoin.tsx, src/pages/indexer/MyPlans/Create/Create.tsx, src/pages/indexer/MyPlans/List/List.tsx
=> remove usdc related places

.env
=> chore: change cid

package.json, yarn.lock
=> chore: up @subql/apollo-links

package.json, src/containers/Web3.tsx, yarn.lock
- Update @subql/networkc-config
Ticket: [SQN-2018](https://onfinality.atlassian.net/browse/SQN-2018)
=> chore: update network config

src/App.tsx
=> chore: reset test

src/pages/explorer/Home/Home.tsx
=> feat: top network

src/pages/explorer/Home/Home.tsx
=> chore: home page loading

.eslintrc, index.html, package.json, public/sw.js, types/i18next.d.ts, yarn.lock
- Enable service worker.
- For html files, use networkFirst. Always request the network for response.
- For images, use cache first and then fetch from network for next response.
- For js/css, use cache first.
- The regex of html test cases: 
```
[
'*://*/',
'*://*',
'*://*/dashboard',
'*://*/dashboard/',
'*://*/dashboard/xxxx',
'*://*/explorer/?xxx=yyy',
'*://*/explorer/xxx?xxx=yyy',
] // should pass
[
'*://*/xxxx',
'*://*/xxxx/',
'*://*/xxxx/?xxx=hy',
'*://*/xxxx/yyyy?xxx=hy',
] // should not pass
```
```
*://*zxczxczxc
```
Also passed, but it is not a valid suffix, so it's ok.
- The regex of js test cases:
```
[
'xxx.js',
'xxx.js?x=y'
] // should pass
[
'xxx.json',
'aajsbb.xyz',
'xxx.json?v=asdasd',
] // should not pass
```
Ticket: …
=> perf(SQN-2041): service worker

.github/workflows/pr-build.yml, src/hooks/useSortedIndexerDeployments.tsx
=> fix: build type

src/router/routes.ts
=> chore: change doc url

src/containers/ProjectMetadata.ts
- Fix project metadata validation
|before|after|
|-|-|
|<img width="1135" alt="Screenshot 2023-11-06 at 1 54 57 PM" src="https://github.com/subquery/network-app/assets/8177474/be528841-711b-4c27-9275-8a64617fc4fa">|<img width="1683" alt="Screenshot 2023-11-06 at 2 03 10 PM" src="https://github.com/subquery/network-app/assets/8177474/d8170750-0737-41cb-b189-1364855a3b49">|
=> Fix validation for project metadata

src/pages/explorer/Home/Home.tsx
- Fix infinity load when home page load error.
- Use skeleton replace spinner.
- Optimise the loading flow. Make sure user have a progressive experience and don't see flush when load more projects.
=> fix: infinity load when get response error

src/pages/account/Withdrawn/Locked/Home/Locked.tsx, src/pages/account/index.tsx
- Statistics ongoing withdrawals not claimed.
=> fix: use ongoing replace claim for withdrawals

.github/workflows/discord.yml
=> chore: discord

src/components/IPFSImage/IPFSImage.tsx, src/components/ProjectCard/ProjectCard.module.css, src/components/ProjectCard/ProjectCard.tsx, src/pages/explorer/Home/Home.module.css, src/pages/explorer/Home/Home.tsx
- Use skeleton replace spinner.
- Optimise the loading flow. Make sure user have a progressive experience and don't see flush when load more projects.
=> feat: update homepage loading

src/hooks/useLocalProjects.ts, src/hooks/useSortedIndexerDeployments.tsx, src/models.tsx, src/pages/explorer/Home/Home.tsx
- Add search on home.
- Test cases:
1. Search keywords.(name, description, version description)
2. Search keywords & load more.
3. Search keywords when the first load not finish.
4. Search on a poor network environment.
5. Search when interrupt establish cache.
6. Re-load with no keywords after search.
Ticket: [SQN-1919](https://onfinality.atlassian.net/browse/SQN-1919)
=> feat: add search on home

src/components/DeploymentInfo/DeploymentInfo.tsx, src/components/ProjectHeader/ProjectHeader.tsx, src/components/UnsafeWarn/index.tsx, src/hooks/useDeploymentMetadata.tsx, src/pages/consumer/MyOffers/CreateOffer/SelectDeployment/SelectDeployment.tsx, src/pages/explorer/Project/Project.tsx
- Add unsafe warn on project detail & create an offer.
Ticket: [SQN-2082](https://onfinality.atlassian.net/browse/SQN-2082)
=> feat(SQN-2082): add unsafe warn on project detail & offer

src/pages/indexer/MyPlans/Default/Default.tsx, src/pages/indexer/MyPlans/Specific/Specific.tsx
- Fix default/specific plans sort problems.
Ticket: [SQN-2093](https://onfinality.atlassian.net/browse/SQN-2093)
=> feat(SQN-2093): add sort for my plans

src/components/DeploymentInfo/DeploymentInfo.tsx, src/components/ProjectHeader/ProjectHeader.tsx, src/components/UnsafeWarn/index.tsx, src/hooks/useDeploymentMetadata.tsx, src/hooks/useLocalProjects.ts, src/hooks/useSortedIndexerDeployments.tsx, src/models.tsx, src/pages/consumer/MyOffers/CreateOffer/SelectDeployment/SelectDeployment.tsx, src/pages/explorer/Home/Home.tsx, src/pages/explorer/Project/Project.tsx, src/pages/indexer/MyPlans/Default/Default.tsx, src/pages/indexer/MyPlans/Specific/Specific.tsx
=> feat: kepler updates

src/pages/delegator/DoDelegate/DoDelegate.module.less
- In prod environment, line-height is not render as expect.
=> fix: line-height on select in prod

src/hooks/useLocalProjects.ts, src/pages/explorer/Home/Home.tsx
- Add disable for input when fetching.
- Fix infinity loading if there have project added.
=> fix: home search

src/hooks/useAirdropKyc.ts
=> chore: reset kyc

src/index.less, src/pages/consumer/MyOffers/MyOffers.module.css, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/DoDelegate/DoDelegate.module.less, src/pages/indexer/MyPlans/Create/Create.module.less, src/pages/indexer/MyPlans/Create/Create.tsx, src/pages/indexer/MyPlans/Plans.module.css
- Fix `Create Plan` style issue.
- Replace primary background color.
- Fix Delegator form style issue.
=> fix: styles

src/hooks/useProjectList.tsx
- Fix a mistake when loading projects.
=> fix: loading status

src/pages/studio/Create/Create.tsx
=> chore: remove test condition

src/hooks/useSortedIndexerDeployments.tsx
=> fix: types

src/hooks/useStudio.ts
It's a useless error report, hidden it.
=> fix: hidden useless error

package.json, yarn.lock
Upgrade to @subql/apollo-links@1.3.0.
=> chore: Upgrade to @subql/apollo-links@1.3.0.

src/pages/swap/Swap.tsx
=> feat: swap wordings

src/utils/dateFormatters.ts
=> fix: format

src/components/Status/Status.module.css, src/containers/QueryApolloProvider.tsx, src/pages/account/Withdrawn/Locked/Home/Locked.tsx, src/pages/explorer/Project/Project.tsx
- Set `no-cache` for apollo-client.
- If indexer is not an indexer any more. Forbid user cancel the stake.
=> feat: style

package.json, src/pages/consumer/MyOffers/MyOffers.tsx, src/pages/consumer/OfferMarketplace/AcceptOffer.tsx, src/pages/consumer/OfferMarketplace/CheckList.tsx, yarn.lock
- Add default mmr root hash.
- Refetch data if it is first time fetch data.
=> feat: offer

src/components/Expand/Expand.tsx, src/components/ProjectDeployments/ProjectDeployments.tsx, src/hooks/useCreateDeployment.tsx
=> fix: edit deloyment

src/pages/dashboard/index.tsx, src/pages/indexer/MyDelegators/MyDelegators.module.css, src/pages/indexer/MyProjects/MyProjects.module.css, src/pages/indexer/MyStaking/MyStaking.module.css, src/pages/indexer/MyStaking/MyStaking.tsx
- If eraIdx is not current era, show the next for the current value.
- Fix style issue.
=> fix: style issue & next delegate stake value.

package.json, src/components/ProjectOverview/ProjectOverview.tsx, yarn.lock
- Adjust markdown body & title style.
- Adjust project main title style.
- Adjust project overview scale.
- Adjust RPC project overview order.
=> feat: adjust project detail

package.json, yarn.lock
=> Update @subql/apollo-links to version 1.3.2

src/config/rainbowConf.tsx
=> Enable `coinbase wallet`

src/pages/swap/Swap.tsx
- Fix the message in swap page
- Apply the message to both `ksqt->usdc` and `usdc-ksqt` pool
- Comment out swap feature codes to avoid unnecessary request to load the page
=> Totally disabled the swap feature in swap page

src/pages/delegator/IndexerDetails/IndexerDetails.tsx, src/pages/indexer/IndexerProfile/IndexerProfile.tsx, src/pages/indexer/MyDelegators/MyDelegators.module.css, src/pages/indexer/MyDelegators/MyDelegators.tsx, src/pages/indexer/MyDelegators/OwnDelegator.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx, yarn.lock
=> feat: change empty status on my projects & my delegators

.github/workflows/mainnet-prod-pipeline
Add the mainnet prod pipeline file
=> chore: add Mainnet-Prod pipeline

.github/workflows/mainnet-prod-pipeline.yml
=> chore: mainnet prod pipeline

.env, .env.staging, .env.testnet, package.json, src/pages/swapksqt/index.tsx, src/pages/swapksqt/success/index.tsx, src/router/routes.ts, yarn.lock
=> feat: swap kSQT to SQT

src/pages/swapksqt/index.tsx
=> feat: update display ratio

src/config/rainbowConf.tsx
=> feat: add coinbase support

src/components/Header/Header.module.less, src/utils/links.ts
=> fix: change Swap to Bridge.

src/pages/swapksqt/index.tsx
=> feat: change total stake to own stake

src/pages/swapksqt/success/index.tsx
=> feat: open new link

src/pages/explorer/Home/Home.tsx
- Fix a bug that didn't show 0x06.
=> feat: lost project

src/pages/delegator/AllIndexers/AllIndexers.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx
- Fix all indexer bug.
- Fix my Projects bug.
=> fix: all indexer & my projects

src/hooks/useSortedIndexerDeployments.tsx
=> fix: own deployment status

.github/workflows/mainnet-prod-pipeline.yml
=> chord: replace aws access key for mainnet prod pipeline

src/containers/QueryApolloProvider.tsx, src/pages/bridge/index.tsx, src/utils/parseError.ts
- Improve error report when call transaction failed.
- Skip approval transaction.
=> feat: Skip approval if input amount less than approved amount.

.env, .env.staging
- Change a cid for use decentralise network.
=> fix: change cid

src/pages/bridge/index.tsx, src/utils/parseError.ts
- Set max gas fee for base to eth.
=> feat: set max gas fee

.github/workflows/dev-build.yml, .github/workflows/mainnet-prod-pipeline.yml, .github/workflows/pr-build.yml, .github/workflows/prod-build.yml, .github/workflows/staging-build.yml
=> chore: change workflow branch

src/components/NumberInput/NumberInput.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/DoUndelegate/DoUndelegate.tsx, src/pages/delegator/MyDelegation.tsx, src/pages/indexer/MyDelegators/OwnDelegator.tsx, src/utils/numberFormatters.ts, src/utils/parseError.ts
Fix: #684 
- Improve reported error, so Sentry can notify on Slack. 
- If user is not an Node runner. Hide the commission.
=> fix: max btn, improve error when report.

src/pages/account/Rewards/Rewards.tsx
=> hotfix: rewards

package.json, src/hooks/useCommissionRate.ts, src/hooks/useSortedIndexer.tsx, src/pages/indexer/MyStaking/SetCommissionRate/SetCommissionRate.tsx, yarn.lock
=> fix: commission

public/manifest.json, src/components/ProjectOverview/ProjectOverview.tsx, src/hooks/useProjectList.tsx, src/pages/dashboard/index.tsx
- Add safe wallet support.
- Change manifest information.
- Improve empty deployment description & project description.
- Temp fix projects loading.
=> fix: add safe wallet, change manifest, improve empty description, temp fix projects loading.

src/hooks/useProjectList.tsx, src/i18n/en/indexer.ts, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx
- Fix pagination & improve type definition of all indexer.
- Fix project list fetching error in some cases.
=> fix: pagination of all indexer

src/hooks/useGetCapacityFromContract.ts, src/hooks/useSortedIndexer.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/DoDelegate/DoDelegate.tsx
- Use contract call replace subql query for indexer's capacity.
=> fix: capacity

src/pages/indexer/MyStaking/SetCommissionRate/SetCommissionRate.tsx
=> fix: default min commission

README.md, package.json, public/manifest.json, yarn.lock
- Change manifest name & readme name.
=> chore: change manifest name

.github/pull_request_template.md, src/components/ProjectCard/ProjectCard.tsx, src/hooks/useProjectList.tsx, src/pages/explorer/Home/Home.tsx, src/pages/projects/Home/Home.tsx, tsconfig.json
=> feat: improve projects

src/components/APYTooltip/index.tsx, src/components/SummaryList/SummaryList.tsx, src/components/index.ts, src/pages/dashboard/index.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/MyDelegation.tsx, src/pages/delegator/TopIndexers/TopIndexersList.tsx
=> Add APY tooltip everywhere

src/components/DoAllocate/DoAllocate.tsx, src/config/rainbowConf.tsx, src/hooks/useEthersProvider.ts, src/utils/numberFormatters.ts
- Fix allocation rounding for existing allocation.
- Fix estimated calculate.
- Add fallback for RPC provider.
=> feat & fix: allocation rounding, estimated calculate, add fallback for RPC.

package.json, src/components/ConnectWallet/ChainStatus.tsx, src/components/DoAllocate/DoAllocate.tsx, src/components/Expand/Expand.tsx, src/components/GetEndpoint/index.tsx, src/components/Icons/Icons.module.less, src/components/ProjectDeployments/ProjectDeployments.tsx, src/components/TransactionModal/TransactionModal.module.less, src/components/TransactionModal/TransactionModal.tsx, src/index.less, src/pages/bridge/index.tsx, src/pages/bridge/success/index.tsx, src/pages/consumer/MyBoostedProjects/MyBoostedProjects.tsx, src/pages/consumer/MyFlexPlans/MyHostedPlan/MyHostedPlan.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/DoUndelegate/DoUndelegate.tsx, src/pages/delegator/MyDelegation.tsx, src/pages/delegator/index.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx, src/pages/projects/Project/Project.tsx, src/router/routes.ts, yarn.lock
- Enhance delegator pages table style.
- Enhance delegator pages router link.
- Enhance empty my delegation.
Style of table.
=> feat: enhance style

src/hooks/useProjectList.tsx
- Fixed project scroll load bug.
=> fix: projects debounce

.env.testnet, src/components/LineCharts/index.tsx, src/pages/dashboard/components/RewardsLineChart/RewardsLineChart.tsx
- Change line chart to stack area chart.
- Change dev end gateway.
=> feat: change to stack area

package.json, src/index.tsx, yarn.lock
=> fix: expire

src/components/DoAllocate/DoAllocate.tsx, src/components/IndexerDetails/IndexerName.tsx, src/components/NotificationCentre/index.tsx, src/components/NotificationCentre/useMakeNotification.ts, src/components/NumberInput/NumberInput.module.less, src/components/TransactionModal/TransactionModal.tsx, src/hooks/useLockPeriod.tsx, src/pages/account/Withdrawn/Locked/Home/Locked.tsx, src/pages/delegator/DoDelegate/DoDelegate.tsx, src/pages/delegator/DoUndelegate/DoUndelegate.tsx, src/stores/notification.ts, src/utils/index.tsx, tsconfig.json
- Add increase/decrease commission rate notification.
- Add new operator notification.
- Fixed a bug that cause always alert `low controller balance` notification.
- Fixed a style issue of number input.
- Enhance withdraw render.
- Enhance the available allocation rounding.
=> feat: enhance allocation, enhance displaying of withdraw, more notification.

src/components/NotificationCentre/useMakeNotification.ts, src/components/NotificationCentre/useToastNotificationModal.tsx, src/stores/notification.ts
- Change outdated project notification priority.
=> feat: up outdated project notification priority

src/components/IndexerDetails/Row.tsx, src/components/ProjectCard/ProjectCard.module.css
- Add cache for trail token.
- Add transition for project hover.
=> feat: add cache

src/components/ProjectOverview/ProjectOverview.tsx, src/hooks/useDelegating.tsx
- Add tooltip.
- Fix delegation display.
=> fix: tooltip & delegation display

src/pages/delegator/DoUndelegate/DoUndelegate.tsx
=> chore: text

src/components/DoBooster/index.tsx, src/components/EmptyList/EmptyList.module.css, src/components/EmptyList/EmptyList.tsx, src/pages/consumer/MyBoostedProjects/MyBoostedProjects.tsx
=> feat: boost msg

package.json, src/hooks/useConsumerHostServices.tsx, yarn.lock
=> feat: erc 4321 sign in replace erc721

src/App.tsx, src/hooks/useSortedIndexerDeployments.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx, src/utils/parseError.ts
- Add query rewards & total rewards for projects also support sort.
=> feat: add query rewards and total rewards

src/components/GetEndpoint/index.tsx, src/pages/explorer/Project/Project.tsx, src/pages/projects/Project/Project.tsx
- Enhance breadcrumb.
- Add ws endpoint for polkadot kusama.
=> feat: add ws endpoint for polkadot, kusama. Enhance breadcrumb.

src/components/APYTooltip/index.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx
=> feat: adjust width for my project

src/pages/indexer/MyProjects/AutoReduceOverAllocation/index.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx
=> feat: hide apy for now

src/components/IndexerDetails/IndexerName.tsx, src/utils/links.ts
- Fix operator name not displayed.
- Add professional link.
=> fix: operator name and add professional link

src/components/IndexerDetails/IndexerName.tsx, src/utils/limitation.ts
- Queue the web3 name fetching.
=> feat: improve low priority

src/hooks/useLocalProjects.ts
=> feat: search by name for now

src/components/IndexerDetails/IndexerName.tsx, src/components/TransactionModal/TransactionModal.tsx, src/hooks/useEra.ts, src/hooks/useProjectList.tsx, src/hooks/useSortedIndexer.tsx, src/hooks/useSpaceId.tsx, src/i18n/en/global.ts, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/DoDelegate/DoDelegate.tsx, src/utils/parseError.ts
- Use fetching from backend instead of fetching chain data of era information.
- Add general message tips for failed transaction.
- Improve error tips for projects list.
- Enhance capacity fetching logic.
- Add loading for fetching delegate information.
- Adjust page size of operators list.
- Adjust fetching trigger time of operators list.
- Support search by name when re-delegate.
- Fix duplicate fetching when search by address of re-delegate.
=> perf: optimise chain query, error tips, search, loading.

src/components/CreateFlexPlan/index.tsx, src/pages/explorer/FlexPlans/CreateHostingPlan/CreateHostingPlan.tsx
- Add limit for creating hosting plan.
=> fix: add limit for create hosting plan

src/components/GetEndpoint/index.tsx, src/pages/consumer/MyFlexPlans/MyHostedPlan/MyHostedPlan.tsx
- Support ws for polkadot & kusama.
=> feat: support ws for polkadot & kusama

src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx
=> fix: era value

src/pages/scanner/projectDeploymentRewards/index.tsx, src/pages/scanner/projectDetail/index.tsx
- Fix date of project detail.
- Enhance exp.
=> fix: project detail price

src/config/rainbowConf.tsx
=> fix: add more eth

src/components/ModalClaimIndexerRewards/ModalClaimIndexerRewards.tsx, src/hooks/useRewardCollectStatus.tsx
- Wait transaction handled after indexerCatchup.
- Remove lastClaimedEra.
=> fix: rewards collect

src/config/sentryConf.ts, src/pages/delegator/MyDelegation.tsx
- Fix leveragelimit cache issue.
=> fix: my delegation

src/components/IndexerDetails/IndexerDetails.tsx, src/components/IndexerDetails/Row.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx
- Add flex plan price at project detail
=> feat: add flex plan price

src/hooks/useConsumerHostServices.tsx, src/pages/consumer/MyFlexPlans/MyFlexPlans.tsx, src/pages/consumer/MyFlexPlans/MyHostedPlan/MyHostedPlan.tsx
- Fixed spent in 7 days shows an incorrect value.
- Fixed digital of hosting plan spent.
- Add spent of today.
=> fix: past 7 days

src/pages/consumer/MyFlexPlans/MyHostedPlan/MyHostedPlan.tsx
- Fixed the example display a wrong value for consumer `Connect` endpoint.
-
=> fix: connect endpoint example

.github/workflows/dev-build.yml
=> Remove the no-cache field to enable AWS CDN caching

src/components/EmptyList/EmptyList.tsx, src/components/Expand/Expand.tsx, src/hooks/useFetchMetadata.tsx, src/hooks/useIndexerMetadata.tsx, src/models.tsx, src/pages/account/index.tsx, src/pages/indexer/IndexerProfile/IndexerProfile.tsx
- Add node operator information.
=> feat: add operator information

src/components/CreateFlexPlan/index.tsx
=> fix: min hosting plan price

.env, package.json, src/App.tsx, src/globalScalars.d.ts, yarn.lock
=> feat: add ai analytics

src/hooks/useConsumerHostServices.tsx, src/pages/indexer/MyProjects/CurrentEraRewards/index.tsx, src/pages/indexer/MyProjects/LastEraBurntReason/index.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx
- Add history records for burnt reasons.
- Move some chs api.
=> feat: add history for burnt

src/components/ProjectOverview/ProjectOverview.tsx, src/pages/explorer/Project/components/DeploymentRewardsChart.tsx
=> fix: word break of markdown

src/components/AppPageHeader/AppPageHeader.module.css, src/components/AppPageHeader/AppPageHeader.tsx, src/components/CreateFlexPlan/index.tsx, src/components/CurEra/CurEra.tsx, src/components/IndexerDetails/IndexerDetails.tsx, src/components/IndexerDetails/PriceQueries.tsx, src/components/LineChartWithMarkLine/index.module.less, src/components/LineChartWithMarkLine/index.tsx, src/components/ProjectOverview/ProjectOverview.module.less, src/components/ProjectOverview/ProjectOverview.tsx, src/index.less, src/pages/account/AccountHeaders/Headers.module.css, src/pages/account/Rewards/ClaimRewards.module.less, src/pages/account/Rewards/Rewards.tsx, src/pages/account/Staking/index.tsx, src/pages/account/Withdrawn/Locked/Home/Locked.tsx, src/pages/account/index.tsx, src/pages/consumer/MyFlexPlans/MyFlexPlans.tsx, src/pages/consumer/MyOffers/CreateOffer/OfferDetails/OfferDetails.module.css, src/pages/consumer/MyOffers/MyOffers.tsx, src/pages/consumer/OfferMarketplace/Marketplace.tsx, src/pages/consumer/ServiceAgreements/ServiceAgreements.tsx, src/pages/delegator/TopIndexers/TopIndexers.tsx, src/pages/indexer/MyDelegators/MyDelegators.tsx, src/pages/indexer/MyStaking/MyStaking.module.css
- Change the queries chart to supply chart.
- Add supply chart when creating hosting plan.
- Fix lots of style issue for keeping layout stable.
=> feat: change queries charts

src/components/APYTooltip/index.tsx, src/pages/account/index.tsx, src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/MyDelegation.tsx, src/pages/delegator/TopIndexers/TopIndexersList.tsx, src/pages/indexer/MyProjects/OwnDeployments/OwnDeployments.tsx
=> Update previous eras message

src/containers/ProjectRegistry.ts, src/hooks/useProject.tsx, src/pages/projects/Create/Create.tsx, src/pages/projects/Project/Deployments.tsx, src/pages/projects/Project/Project.tsx
- Fixed a bug when create/edit the deployment the refresh process didn't work correctly.
=> fix: refresh after edit deployment

.github/workflows/dev-build.yml, .github/workflows/mainnet-prod-pipeline.yml, .github/workflows/pr-build.yml, .github/workflows/prod-build.yml, .github/workflows/staging-build.yml
Corrected `treaded` to `treated` x5
=> fix: typos in documentation files

.github/workflows/dev-build.yml, .github/workflows/mainnet-prod-pipeline.yml, .github/workflows/pr-build.yml, .github/workflows/prod-build.yml, .github/workflows/staging-build.yml, src/components/BarCharts/index.tsx, src/components/IndexerDetails/Row.tsx
This pull request fixes multiple typos found in various files. These changes improve code clarity and eliminate minor textual errors. The updates do not affect the logic or functionality of the code.
**Ticket:** [#ticket number](https://url-for-ticket)
1. Corrected a recurring typo: `"treaded"` → `"treated"` across multiple build workflow files.
2. Fixed a misalignment issue: `"centrer"` → `"center"` in `BarCharts/index.tsx`.
3. Updated a comment typo: `"can't get exactly expires time"` → `"can't get exact expiration time"` in `IndexerDetails/Row.tsx`.
No dependencies are required for this change.
---
The following tests were performed to validate these changes:
- Verified that the build workflows function as expected without errors.
- Confirmed that the UI alignment for the `BarCharts` …
=> fix: multiple typos of different importance

src/components/TransactionModal/TransactionModal.tsx, src/pages/dashboard/components/RewardsLineChart/RewardsLineChart.tsx, src/pages/delegator/DoDelegate/DoDelegate.tsx
fix some typos in comment
|before|after|
|-|-|
=> chore: fix some typos in comment

src/i18n/en/consumer.ts, src/pages/dashboard/components/RewardsLineChart/RewardsLineChart.tsx
Changes:
1. src/i18n/en/consumer.ts
- paymentAmount: 'Paymeny Amount'
+ paymentAmount: 'Payment Amount'
1. src/pages/dashboard/components/RewardsLineChart/RewardsLineChart.tsx
- //    3. based on 1. and 2. also need to do a lots of things for compatite dev env(1 era < 1 day).
+ //    3. based on 1. and 2. also need to do lots of things for compatible dev env(1 era < 1 day).
Reason: Fixed spelling error ('compatite' to 'compatible') and improved grammar by removing unnecessary article 'a' for better code documentation clarity.
=>  Spelling Issues

src/i18n/en/consumer.ts
=> Fix Spelling Errors

src/components/EmptyList/EmptyList.module.css, src/i18n/en/consumer.ts
=> fix: align

src/components/DoBooster/index.tsx, src/components/FTextInput/FTextInput.module.less, src/components/FTextInput/FTextInput.tsx, src/components/GetEndpoint/index.tsx, src/components/ProjectHeader/ProjectHeader.tsx, src/components/ProjectOverview/ProjectOverview.tsx, src/i18n/en/explorer.ts, src/pages/explorer/Project/type.ts, src/pages/projects/Create/Create.module.less, src/pages/projects/Create/Create.tsx, src/pages/projects/Project/Deployments.tsx, src/pages/projects/Project/Project.tsx
- Polish publish success processing.
=> feat: polish publish project.

src/components/ProjectHeader/ProjectHeader.tsx, src/const/const.ts
- Add Phala Network name.
- If yesterday is 0(actually not 0 but can't statistics) show <1,000 instead of.
=> chore: add network name & update 0 query count

src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx
- Fix float display issue on delegator-all-node-operators page
=> fix: float issue

.env, src/containers/QueryApolloProvider.tsx
=> chore: update ai url

.env
=> chore: change ai url

src/App.tsx
=> chore: remove banner

package.json, yarn.lock
=> chore: upgrade wagmi

src/hooks/useSpaceId.tsx, src/pages/delegator/DoDelegate/DelegateFrom.tsx, src/pages/delegator/DoDelegate/DoDelegate.tsx
=> feat: delegate form

src/pages/delegator/AllIndexers/IndexerList/IndexerList.tsx, src/pages/delegator/MyDelegation.tsx, src/pages/indexer/IndexerProfile/IndexerProfile.tsx
- Update commission rate tooltip.
=> fix: tooltip of commission rate

package.json, src/config/rainbowConf.tsx, yarn.lock
=> chore: update dependency

.github/workflows/dev-build.yml
=> Pipeline: Change Deploy Dev push to new s3

.github/workflows/dev-build.yml, .github/workflows/mainnet-prod-pipeline.yml, .github/workflows/staging-build.yml
=> Pipeline: Change all env's gitops to use variables

src/components/FTextInput/FTextInput.tsx, src/models.tsx, src/pages/projects/Create/Create.module.less, src/pages/projects/Create/Create.tsx
=> feat: required

src/pages/projects/Create/Create.tsx
=> chore: update

src/components/CreateFlexPlan/index.tsx, src/hooks/useProjectList.module.less, src/hooks/useProjectList.tsx
=> feat: add sort

.env, src/components/NotificationCentre/useMakeNotification.ts, src/pages/dashboard/components/ActiveCard/ActiveCard.tsx, src/stores/notification.ts
=> feat: notify

src/pages/dashboard/components/ActiveCard/ActiveCard.tsx
=> fix: count

src/hooks/useVerifyDeployment.ts, src/pages/projects/Create/Create.tsx
=> fix: verify subquery

package.json, src/pages/account/Rewards/ClaimRewards.tsx, src/pages/account/Rewards/Rewards.tsx, yarn.lock
- Directly claim to the stake.
=> feat: directly claim to the stake.

index.html, src/App.tsx
=> chore: gtag

src/components/DoBooster/index.tsx, src/components/IndexerDetails/IndexerDetails.tsx, src/components/ProjectOverview/ProjectOverview.tsx, src/i18n/en/explorer.ts, src/pages/consumer/MyBoostedProjects/MyBoostedProjects.tsx, src/pages/projects/Create/Create.tsx
=> feat: part

index.html
=> chore: replace tag manager
